/*Question_10:--- Adding comments: Choose two of the programs you've written, and add at least one comment toeach. If you don't have anything specific to write becvause your programs are too simple at this point, just add your name and the current date at the top of each program file. Then write one sentence describing what the program does...*/

//This program adds two number and prints the result...
// Define Two numbers...
let number1 = 4;
let number2 = 4;
//Add two numbers...
let result= number1 + number2;
//Print result...
console.log(result);
