/*Question_21:--- They think of something you could store in a TypeScript Object. Write a program that creates Objects containing these items...*/


//  Object is consist of key + value
let studentDetails = {
    name: "Faizan", // This. "name" is key and "Faizan" is value...
    age: 20,        // This. "age" is key and "20" is value...
    gender: "Male", // This. "gender" is key and "Male" is value...
    rollNo: 12345,  // This. "rollNo" is key and "12345" is value...
};
console.log(studentDetails);
